In [23]:
import torch
import numpy as np

In [4]:
a = torch.randn(2,3)
a

tensor([[ 0.5955, -0.4783,  0.5443],
        [-0.3855,  0.9036, -2.2748]])

In [5]:
a.type()

'torch.FloatTensor'

In [6]:
type(a)

torch.Tensor

In [7]:
isinstance(a, torch.FloatTensor)

True

In [8]:
a = a.cuda()

AssertionError: Torch not compiled with CUDA enabled

In [11]:
torch.cuda.is_available()

False

In [12]:
torch.tensor(1.)

tensor(1.)

In [13]:
torch.tensor(1.3)

tensor(1.3000)

In [14]:
a.shape

torch.Size([2, 3])

In [15]:
torch.tensor(2.2).shape

torch.Size([])

In [16]:
len(a.shape)

2

In [17]:
a.size()

torch.Size([2, 3])

In [18]:
torch.tensor([1.1])

tensor([1.1000])

In [19]:
torch.tensor([1.1, 2.2])

tensor([1.1000, 2.2000])

In [20]:
torch.FloatTensor(1)

tensor([2.])

In [21]:
torch.FloatTensor(2)

tensor([1.4013e-45, 0.0000e+00])

In [32]:
data = np.ones(2)
print(data)
print(torch.from_numpy(data))

[1. 1.]
tensor([1., 1.], dtype=torch.float64)


NameError: name 'array' is not defined