In [2]:
import torch
import numpy as np

In [5]:
arr = np.ones((3,3))
print(arr)
arr.dtype

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


dtype('float64')

In [7]:
t1 = torch.tensor(arr)
print(t1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [9]:
t2 = torch.tensor(arr,device='cpu')
print(t2)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [5]:
arr2 = np.array([[1,2,3],[4,5,6]])
t = torch.from_numpy(arr2)
print(t)
# 这个方法创建的张量会随arr2的改变而改变，类似于浅拷贝

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
