In [1]:
import torch

In [14]:
a = torch.rand(3,4)
b = torch.rand(3,4)

TypeError: randint(): argument 'size' (position 2) must be tuple of ints, not int

In [3]:
print(a)
print(b)

tensor([[0.6506, 0.3147, 0.2792, 0.1694],
        [0.1674, 0.5908, 0.5395, 0.6585],
        [0.3604, 0.6695, 0.9078, 0.3052]])
tensor([[4.0165e-01, 7.5565e-01, 4.9688e-01, 1.3313e-01],
        [7.0681e-01, 7.3683e-01, 1.3942e-04, 4.1306e-01],
        [3.1088e-01, 2.3650e-01, 6.4853e-02, 5.5721e-01]])


In [5]:
# print(a+b)
# print(torch.add(a,b))

c = torch.Tensor(3,4)
print(torch.add(a,b,out=c))

tensor([[1.0522, 1.0704, 0.7760, 0.3025],
        [0.8742, 1.3276, 0.5397, 1.0716],
        [0.6713, 0.9060, 0.9727, 0.8624]])
tensor([[1.0522, 1.0704, 0.7760, 0.3025],
        [0.8742, 1.3276, 0.5397, 1.0716],
        [0.6713, 0.9060, 0.9727, 0.8624]])
tensor([[1.0522, 1.0704, 0.7760, 0.3025],
        [0.8742, 1.3276, 0.5397, 1.0716],
        [0.6713, 0.9060, 0.9727, 0.8624]])


In [10]:
# print(a-b)
torch.sub(a,b)

tensor([[ 0.2489, -0.4410, -0.2177,  0.0362],
        [-0.5394, -0.1460,  0.5394,  0.2455],
        [ 0.0495,  0.4330,  0.8430, -0.2520]])


tensor([[ 0.2489, -0.4410, -0.2177,  0.0362],
        [-0.5394, -0.1460,  0.5394,  0.2455],
        [ 0.0495,  0.4330,  0.8430, -0.2520]])

In [12]:
# a*b
torch.mul(a,b)

tensor([[2.6130e-01, 2.3780e-01, 1.3871e-01, 2.2549e-02],
        [1.1832e-01, 4.3530e-01, 7.5216e-05, 2.7202e-01],
        [1.1203e-01, 1.5834e-01, 5.8874e-02, 1.7005e-01]])

In [16]:
# a/b
torch.div(a,b)

tensor([[1.6198e+00, 4.1646e-01, 5.6184e-01, 1.2722e+00],
        [2.3684e-01, 8.0179e-01, 3.8698e+03, 1.5943e+00],
        [1.1592e+00, 2.8310e+00, 1.3998e+01, 5.4770e-01]])

In [17]:
a

tensor([[0.6506, 0.3147, 0.2792, 0.1694],
        [0.1674, 0.5908, 0.5395, 0.6585],
        [0.3604, 0.6695, 0.9078, 0.3052]])

In [19]:
# a.pow(2)
a**2

tensor([[0.4232, 0.0990, 0.0779, 0.0287],
        [0.0280, 0.3490, 0.2911, 0.4337],
        [0.1299, 0.4483, 0.8241, 0.0931]])