In [2]:
import torch

In [3]:
x = torch.arange(12)

In [4]:
torch.Size([12])

torch.Size([12])

In [6]:
x.numel()

12

In [8]:
X = x.reshape(3,4)
print(X)
print(x)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [3]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [4]:
torch.randn(3,4)

tensor([[ 0.0713, -0.8411,  0.2284, -0.4472],
        [ 1.0370,  0.9702, -0.0863,  0.5098],
        [ 1.4692,  0.2108, -1.6154,  0.4102]])

In [5]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [ ]:
A=torch.arange(12, dtype)